import { Film } from '../types'
import type { Recommendation } from '../services/llm'

export const MOCK_DELAY_MS = 800

export const MOCK_USERNAME = 'dev_user'

export const MOCK_WATCHLIST: Film[] = [
  {
    title: 'Past Lives',
    year: '2023',
    slug: 'past-lives',
    poster: 'https://picsum.photos/seed/pastlives/500/750',
    overview: "Nora and Hae Sung, two deeply connected childhood friends, are separated after Nora's family emigrates from South Korea. Twenty years later, they reunite in New York.",
    tmdb_id: 1029782,
    genres: ['Drame', 'Romance'],
    runtime: 106,
    providers: ['Canal+'],
    tmdb_url: 'https://www.themoviedb.org/movie/1029782',
  },
  {
    title: 'Oppenheimer',
    year: '2023',
    slug: 'oppenheimer',
    poster: 'https://picsum.photos/seed/oppenheimer/500/750',
    overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    tmdb_id: 872585,
    genres: ['Drame', 'Histoire'],
    runtime: 180,
    providers: ['Prime Video'],
    tmdb_url: 'https://www.themoviedb.org/movie/872585',
  },
  {
    title: 'The Zone of Interest',
    year: '2023',
    slug: 'the-zone-of-interest',
    poster: 'https://picsum.photos/seed/zoneofinterest/500/750',
    overview: "The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig strive to build a dream life for their family in a house and garden next to the camp.",
    tmdb_id: 849422,
    genres: ['Drame', 'Histoire', 'Guerre'],
    runtime: 105,
    providers: ['MUBI'],
    tmdb_url: 'https://www.themoviedb.org/movie/849422',
  },
  {
    title: 'Poor Things',
    year: '2023',
    slug: 'poor-things',
    poster: 'https://picsum.photos/seed/poorthings/500/750',
    overview: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    tmdb_id: 792307,
    genres: ['Science-Fiction', 'Romance', 'Comédie'],
    runtime: 141,
    providers: ['Disney+'],
    tmdb_url: 'https://www.themoviedb.org/movie/792307',
  },
  {
    title: 'Anatomy of a Fall',
    year: '2023',
    slug: 'anatomy-of-a-fall',
    poster: 'https://picsum.photos/seed/anatomyfall/500/750',
    overview: "A woman is suspected of her husband's murder after he's found dead below their chalet in the French Alps. A year later, the trial begins.",
    tmdb_id: 1010600,
    genres: ['Drame', 'Thriller'],
    runtime: 150,
    providers: ['Canal+'],
    tmdb_url: 'https://www.themoviedb.org/movie/1010600',
  },
  {
    title: 'Talk to Me',
    year: '2022',
    slug: 'talk-to-me',
    poster: 'https://picsum.photos/seed/talktome/500/750',
    overview: "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new rush — until one of them goes too far.",
    tmdb_id: 1008042,
    genres: ['Horreur', 'Thriller'],
    runtime: 95,
    providers: ['Prime Video'],
    tmdb_url: 'https://www.themoviedb.org/movie/1008042',
  },
  {
    title: 'Spider-Man: Across the Spider-Verse',
    year: '2023',
    slug: 'spider-man-across-the-spider-verse',
    poster: 'https://picsum.photos/seed/spiderspiderverse/500/750',
    overview: "Miles Morales catapults across the multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    tmdb_id: 569094,
    genres: ['Animation', 'Action', 'Science-Fiction'],
    runtime: 140,
    providers: ['Netflix'],
    tmdb_url: 'https://www.themoviedb.org/movie/569094',
  },
  {
    title: 'The Holdovers',
    year: '2023',
    slug: 'the-holdovers',
    poster: 'https://picsum.photos/seed/holdovers/500/750',
    overview: "A cranky history teacher at a New England prep school is forced to remain on campus over the holidays with a troubled student who has nowhere to go.",
    tmdb_id: 840430,
    genres: ['Comédie', 'Drame'],
    runtime: 133,
    providers: ['Prime Video'],
    tmdb_url: 'https://www.themoviedb.org/movie/840430',
  },
  {
    title: 'Saltburn',
    year: '2023',
    slug: 'saltburn',
    poster: 'https://picsum.photos/seed/saltburn/500/750',
    overview: "A student at Oxford University finds himself drawn into the world of a charming and aristocratic classmate, who invites him to his eccentric family's sprawling estate.",
    tmdb_id: 1010581,
    genres: ['Thriller', 'Drame'],
    runtime: 131,
    providers: ['Prime Video'],
    tmdb_url: 'https://www.themoviedb.org/movie/1010581',
  },
  {
    title: 'Killers of the Flower Moon',
    year: '2023',
    slug: 'killers-of-the-flower-moon',
    poster: 'https://picsum.photos/seed/killers/500/750',
    overview: "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one — until the FBI steps in to unravel the mystery.",
    tmdb_id: 466420,
    genres: ['Crime', 'Drame', 'Histoire'],
    runtime: 206,
    providers: ['Apple TV+'],
    tmdb_url: 'https://www.themoviedb.org/movie/466420',
  },
  {
    title: 'Priscilla',
    year: '2023',
    slug: 'priscilla',
    poster: 'https://picsum.photos/seed/priscilla/500/750',
    overview: "When teenage Priscilla Beaulieu meets Elvis Presley at a party, the man who is already a meteoric rock-and-roll superstar becomes someone entirely unexpected.",
    tmdb_id: 944423,
    genres: ['Drame', 'Romance', 'Biographie'],
    runtime: 113,
    providers: ['MUBI'],
    tmdb_url: 'https://www.themoviedb.org/movie/944423',
  },
  {
    title: 'Robot Dreams',
    year: '2023',
    slug: 'robot-dreams',
    poster: 'https://picsum.photos/seed/robotdreams/500/750',
    overview: "Dog builds himself a robot companion but one summer's end, he is forced to leave Robot on the beach, unable to get him back.",
    tmdb_id: 1081291,
    genres: ['Animation', 'Drame', 'Famille'],
    runtime: 102,
    providers: ['Canal+'],
    tmdb_url: 'https://www.themoviedb.org/movie/1081291',
  },
  {
    title: 'Godzilla Minus One',
    year: '2023',
    slug: 'godzilla-minus-one',
    poster: 'https://picsum.photos/seed/godzilla/500/750',
    overview: "Postwar Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.",
    tmdb_id: 926393,
    genres: ['Action', 'Science-Fiction', 'Horreur'],
    runtime: 125,
    providers: ['Netflix'],
    tmdb_url: 'https://www.themoviedb.org/movie/926393',
  },
  {
    title: 'Beau Is Afraid',
    year: '2023',
    slug: 'beau-is-afraid',
    poster: 'https://picsum.photos/seed/beauisafraid/500/750',
    overview: "Following the sudden death of his mother, a paranoid man embarks on an epic odyssey to get home.",
    tmdb_id: 882598,
    genres: ['Horreur', 'Drame', 'Fantastique'],
    runtime: 179,
    providers: [],
    tmdb_url: 'https://www.themoviedb.org/movie/882598',
  },
  {
    title: 'All of Us Strangers',
    year: '2023',
    slug: 'all-of-us-strangers',
    poster: 'https://picsum.photos/seed/allofusstrangers/500/750',
    overview: "A screenwriter living alone in a near-empty tower block begins a relationship with his mysterious neighbour, while he is simultaneously drawn back to his childhood home.",
    tmdb_id: 1056360,
    genres: ['Drame', 'Romance', 'Fantastique'],
    runtime: 105,
    providers: ['Disney+'],
    tmdb_url: 'https://www.themoviedb.org/movie/1056360',
  },
]

// MOCK_RECOMMENDATION.title must match a film in MOCK_WATCHLIST
export const MOCK_RECOMMENDATION: Recommendation = {
  title: 'Past Lives',
  reason: "Pour une soirée contemplative, ce film t'emmènera dans une réflexion douce sur le temps et les chemins non pris.",
  match_score: 92,
  mood_tags: ['mélancolie douce', 'amour', 'identité'],
  warning: null,
}

export const MOCK_TEST_KEY_RESPONSE = { status: 'ok' } as const
